# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KaryaKram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('unit', models.CharField(max_length=15)),
                ('kriyakalap', models.CharField(blank=True, max_length=15, null=True)),
                ('karyakram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='reports.KaryaKram')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyakram', to='office.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Lakxya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paridam', models.FloatField(default=0.0)),
                ('var', models.FloatField(default=0.0)),
                ('budget', models.FloatField(default=0.0)),
                ('awadhi', models.IntegerField(choices=[(0, 'barsik'), (1, 'patham'), (2, 'ditiya'), (3, 'tesro')], default=0)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lakxya', to='reports.FiscalYear')),
                ('karyakram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lakxya', to='reports.KaryaKram')),
            ],
        ),
        migrations.CreateModel(
            name='LakxyaHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paridam', models.FloatField(default=0.0)),
                ('var', models.FloatField(default=0.0)),
                ('budget', models.FloatField(default=0.0)),
                ('lakxya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.Lakxya')),
            ],
        ),
        migrations.CreateModel(
            name='Pragati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paridam', models.FloatField(default=0.0)),
                ('var', models.FloatField(default=0.0)),
                ('budget', models.FloatField(default=0.0)),
                ('awadhi', models.IntegerField(choices=[(0, 'barsik'), (1, 'patham'), (2, 'ditiya'), (3, 'tesro')], default=1)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pragati', to='reports.FiscalYear')),
                ('karyakram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pragati', to='reports.KaryaKram')),
            ],
        ),
        migrations.CreateModel(
            name='PragatiHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paridam', models.FloatField(default=0.0)),
                ('var', models.FloatField(default=0.0)),
                ('budget', models.FloatField(default=0.0)),
                ('pragati', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.Pragati')),
            ],
        ),
    ]
