# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyakram',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0915\u094b\u0921'),
        ),
        migrations.AlterField(
            model_name='karyakram',
            name='kriyakalap',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0915\u0943\u092f\u093e\u0915\u0932\u093e\u092a'),
        ),
        migrations.AlterField(
            model_name='karyakram',
            name='unit',
            field=models.CharField(max_length=15, verbose_name='\u092f\u0941\u0928\u093f\u091f'),
        ),
        migrations.AlterField(
            model_name='lakxya',
            name='awadhi',
            field=models.IntegerField(choices=[(0, '\u092c\u093e\u0930\u094d\u0937\u093f\u0915'), (1, '\u092a\u094d\u0930\u0925\u092e'), (2, '\u0926\u093f\u0924\u093f\u092f'), (3, '\u0924\u0943\u0924\u0940\u092f')], default=0, verbose_name='\u0905\u0935\u0927\u093f'),
        ),
        migrations.AlterField(
            model_name='lakxya',
            name='budget',
            field=models.FloatField(default=0.0, verbose_name='\u092c\u091c\u0947\u091f'),
        ),
        migrations.AlterField(
            model_name='lakxya',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lakxya', to='reports.FiscalYear', verbose_name='\u0906\u0930\u094d\u0925\u093f\u0915-\u0935\u0930\u094d\u0937'),
        ),
        migrations.AlterField(
            model_name='lakxya',
            name='karyakram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lakxya', to='reports.KaryaKram', verbose_name='\u0915\u093e\u0930\u094d\u092f\u0915\u094d\u0930\u092e'),
        ),
        migrations.AlterField(
            model_name='lakxya',
            name='paridam',
            field=models.FloatField(default=0.0, verbose_name='\u092a\u0930\u093f\u0926\u092e'),
        ),
        migrations.AlterField(
            model_name='lakxya',
            name='var',
            field=models.FloatField(default=0.0, verbose_name='\u092d\u093e\u0930'),
        ),
        migrations.AlterField(
            model_name='lakxyahistory',
            name='budget',
            field=models.FloatField(default=0.0, verbose_name='\u092c\u091c\u0947\u091f'),
        ),
        migrations.AlterField(
            model_name='lakxyahistory',
            name='paridam',
            field=models.FloatField(default=0.0, verbose_name='\u092a\u0930\u093f\u0926\u092e'),
        ),
        migrations.AlterField(
            model_name='lakxyahistory',
            name='var',
            field=models.FloatField(default=0.0, verbose_name='\u092d\u093e\u0930'),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='awadhi',
            field=models.IntegerField(choices=[(0, '\u092c\u093e\u0930\u094d\u0937\u093f\u0915'), (1, '\u092a\u094d\u0930\u0925\u092e'), (2, '\u0926\u093f\u0924\u093f\u092f'), (3, '\u0924\u0943\u0924\u0940\u092f')], default=1, verbose_name='\u0905\u0935\u0927\u093f'),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='budget',
            field=models.FloatField(default=0.0, verbose_name='\u092c\u091c\u0947\u091f'),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pragati', to='reports.FiscalYear', verbose_name='\u0906\u0930\u094d\u0925\u093f\u0915-\u0935\u0930\u094d\u0937'),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='karyakram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pragati', to='reports.KaryaKram', verbose_name='\u0915\u093e\u0930\u094d\u092f\u0915\u094d\u0930\u092e'),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='paridam',
            field=models.FloatField(default=0.0, verbose_name='\u092a\u0930\u093f\u0926\u092e'),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='var',
            field=models.FloatField(default=0.0, verbose_name='\u092d\u093e\u0930'),
        ),
        migrations.AlterField(
            model_name='pragatihistory',
            name='budget',
            field=models.FloatField(default=0.0, verbose_name='\u092c\u091c\u0947\u091f'),
        ),
        migrations.AlterField(
            model_name='pragatihistory',
            name='paridam',
            field=models.FloatField(default=0.0, verbose_name='\u092a\u0930\u093f\u0926\u092e'),
        ),
        migrations.AlterField(
            model_name='pragatihistory',
            name='var',
            field=models.FloatField(default=0.0, verbose_name='\u092d\u093e\u0930'),
        ),
    ]
