# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170622_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyakram',
            name='karyakram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='reports.KaryaKram', verbose_name='\u0915\u093e\u0930\u094d\u092f\u0915\u094d\u0930\u092e'),
        ),
        migrations.AlterField(
            model_name='karyakram',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyakram', to='office.Office', verbose_name='\u0915\u093e\u0930\u094d\u092f\u093e\u0932\u092f'),
        ),
        migrations.AlterField(
            model_name='lakxyahistory',
            name='lakxya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.Lakxya', verbose_name='\u0932\u0915\u094d\u0937\u094d\u092f'),
        ),
        migrations.AlterField(
            model_name='pragatihistory',
            name='pragati',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.Pragati', verbose_name='\u092a\u094d\u0930\u0917\u0924\u0940'),
        ),
    ]
