# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_auto_20170624_1756'),
        ('reports', '0003_auto_20170623_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='reports.FiscalYear', verbose_name='Arthik Barsa')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='office.Office', verbose_name='')),
            ],
        ),
    ]
