# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('district_np', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kendra', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('no_of_wards', models.TextField(blank=True)),
                ('population', models.CharField(blank=True, max_length=30)),
                ('activities', models.TextField(blank=True)),
                ('mayor_name', models.CharField(max_length=30)),
                ('mayor_phone_no', models.CharField(max_length=30)),
                ('mayor_address', models.CharField(blank=True, max_length=30)),
                ('sub_mayor_name', models.CharField(max_length=30)),
                ('sub_mayor_phone_no', models.CharField(max_length=30)),
                ('sub_mayor_address', models.CharField(blank=True, max_length=30)),
                ('ward_chief_details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('office_time', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ompimage')),
                ('is_municipality', models.BooleanField(default=False)),
                ('is_project', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Department')),
                ('district', models.ManyToManyField(related_name='office', to='office.District')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_time', models.CharField(max_length=30)),
                ('budget', models.CharField(max_length=30)),
                ('objective', models.TextField(blank=True)),
                ('chief_eng', models.CharField(blank=True, max_length=30)),
                ('engineers', models.TextField(blank=True)),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_detail', to='office.Office')),
            ],
        ),
        migrations.AddField(
            model_name='municipalitydetail',
            name='office',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='municipality_detail', to='office.Office'),
        ),
        migrations.AddField(
            model_name='department',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='office.Ministry'),
        ),
    ]
