# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0928\u093e\u092e')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255, verbose_name='\u091c\u093f\u0932\u094d\u0932\u093e')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0928\u093e\u092e')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kendra', models.CharField(max_length=30, verbose_name='\u0915\u0947\u0928\u094d\u0926\u094d\u0930')),
                ('area', models.CharField(max_length=30, verbose_name='\u090f\u0930\u093f\u092f\u093e')),
                ('no_of_wards', models.TextField(blank=True, verbose_name='\u0935\u0921\u093e\u0939\u0930\u0941 \u0915\u094b \u0938\u0902\u0916\u094d\u092f\u093e')),
                ('population', models.CharField(blank=True, max_length=30, verbose_name='\u091c\u0928\u0938\u0902\u0916\u094d\u092f\u093e')),
                ('activities', models.TextField(blank=True, verbose_name='\u0915\u0943\u092f\u093e\u0915\u0932\u093e\u092a\u0939\u0930\u0941')),
                ('mayor_name', models.CharField(max_length=30, verbose_name='\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u0915\u094b \u0928\u093e\u092e')),
                ('mayor_phone_no', models.CharField(max_length=30, verbose_name='\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u0915\u094b \u092b\u094b\u0928')),
                ('mayor_address', models.CharField(blank=True, max_length=30, verbose_name='\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u0915\u094b \u0920\u0947\u0917\u093e\u0928\u093e ')),
                ('sub_mayor_name', models.CharField(max_length=30, verbose_name='\u0909\u092a-\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u0915\u094b \u0928\u093e\u092e')),
                ('sub_mayor_phone_no', models.CharField(max_length=30, verbose_name='\u0909\u092a-\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u0915\u094b \u092b\u094b\u0928')),
                ('sub_mayor_address', models.CharField(blank=True, max_length=30, verbose_name='\u0909\u092a-\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u0915\u094b \u0920\u0947\u0917\u093e\u0928\u093e ')),
                ('ward_chief_details', models.TextField(blank=True, verbose_name='\u0935\u0921\u093e \u092a\u094d\u0930\u092e\u0941\u0916\u0915\u094b \u0935\u093f\u0935\u0930\u0923 ')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0928\u093e\u092e')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='\u0920\u0947\u0917\u093e\u0928\u093e')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='\u0907\u092e\u0947\u0932')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='\u092b\u094b\u0928')),
                ('fax', models.CharField(blank=True, max_length=255, verbose_name='\u092b\u094d\u092f\u093e\u0915\u0938')),
                ('office_time', models.CharField(blank=True, max_length=255, verbose_name='\u0915\u093e\u0930\u094d\u092f\u093e\u0932\u092f \u0938\u092e\u092f')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ompimage', verbose_name='\u0924\u0938\u094d\u092c\u093f\u0930')),
                ('is_municipality', models.BooleanField(default=False, verbose_name='\u0928\u0917\u0930\u092a\u093e\u0932\u093f\u0915\u093e')),
                ('is_project', models.BooleanField(default=False, verbose_name='\u0906\u092f\u094b\u091c\u0928\u093e')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Department', verbose_name='\u092c\u093f\u092d\u093e\u0917')),
                ('district', models.ManyToManyField(related_name='office', to='office.District', verbose_name='\u091c\u093f\u0932\u094d\u0932\u093e')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='office.Office', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_time', models.CharField(max_length=30, verbose_name='\u0906\u092f\u094b\u091c\u0928\u093e\u0915\u094b \u0938\u092e\u092f')),
                ('budget', models.CharField(max_length=30, verbose_name='\u092c\u091c\u0947\u091f')),
                ('objective', models.TextField(blank=True, verbose_name='\u0909\u0926\u094d\u0926\u0947\u0938\u094d\u092f')),
                ('chief_eng', models.CharField(blank=True, max_length=30, verbose_name='\u092c\u0930\u093f\u0938\u094d\u0920  \u0907\u0928\u094d\u091c\u093f\u0928\u0940\u092f\u0930')),
                ('engineers', models.TextField(blank=True, verbose_name=' \u0907\u0928\u094d\u091c\u093f\u0928\u0940\u092f\u0930\u0939\u0930\u0941')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_detail', to='office.Office', verbose_name='\u0915\u093e\u0930\u094d\u092f\u093e\u0932\u092f')),
            ],
        ),
        migrations.AddField(
            model_name='municipalitydetail',
            name='office',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='municipality_detail', to='office.Office', verbose_name='\u0915\u093e\u0930\u094d\u092f\u093e\u0932\u092f'),
        ),
        migrations.AddField(
            model_name='department',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='office.Ministry', verbose_name='\u092e\u0928\u094d\u0924\u094d\u0930\u093e\u0932\u092f'),
        ),
    ]
