# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipalitydetail',
            name='office',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='office',
        ),
        migrations.RemoveField(
            model_name='office',
            name='is_municipality',
        ),
        migrations.RemoveField(
            model_name='office',
            name='is_project',
        ),
        migrations.DeleteModel(
            name='MunicipalityDetail',
        ),
        migrations.DeleteModel(
            name='ProjectDetail',
        ),
    ]
