# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_np',
        ),
        migrations.AlterField(
            model_name='department',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='office.Ministry', verbose_name='\u092e\u0928\u094d\u0924\u094d\u0930\u093e\u0932\u092f'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u0928\u093e\u092e'),
        ),
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(max_length=255, verbose_name='\u091c\u093f\u0932\u094d\u0932\u093e'),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='activities',
            field=models.TextField(blank=True, verbose_name='\u0915\u0943\u092f\u093e\u0915\u0932\u093e\u092a\u0939\u0930\u0941'),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='area',
            field=models.CharField(max_length=30, verbose_name='\u090f\u0930\u093f\u092f\u093e'),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='kendra',
            field=models.CharField(max_length=30, verbose_name='\u0915\u0947\u0928\u094d\u0926\u094d\u0930'),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='mayor_address',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u0915\u094b \u0920\u0947\u0917\u093e\u0928\u093e '),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='mayor_name',
            field=models.CharField(max_length=30, verbose_name='\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u0915\u094b \u0928\u093e\u092e'),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='mayor_phone_no',
            field=models.CharField(max_length=30, verbose_name='\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u0915\u094b \u092b\u094b\u0928'),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='no_of_wards',
            field=models.TextField(blank=True, verbose_name='\u0935\u0921\u093e\u0939\u0930\u0941 \u0915\u094b \u0938\u0902\u0916\u094d\u092f\u093e'),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='office',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='municipality_detail', to='office.Office', verbose_name='\u0915\u093e\u0930\u094d\u092f\u093e\u0932\u092f'),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='population',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u091c\u0928\u0938\u0902\u0916\u094d\u092f\u093e'),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='sub_mayor_address',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u0909\u092a-\u092a\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u094b \u0920\u0947\u0917\u093e\u0928\u093e '),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='sub_mayor_name',
            field=models.CharField(max_length=30, verbose_name='\u0909\u092a-\u092a\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u094b \u0928\u093e\u092e'),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='sub_mayor_phone_no',
            field=models.CharField(max_length=30, verbose_name='\u0909\u092a-\u092a\u092e\u092f\u0947\u0930/\u0905\u0927\u094d\u092f\u0915\u094d\u0937\u094b \u092b\u094b\u0928'),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='ward_chief_details',
            field=models.TextField(blank=True, verbose_name='\u0935\u0921\u093e\u092a\u094d\u0930\u092e\u0941\u0916\u0915\u094b\u0935\u093f\u0935\u0930\u0923 '),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0920\u0947\u0917\u093e\u0928\u093e'),
        ),
        migrations.AlterField(
            model_name='office',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Department', verbose_name='\u092c\u093f\u092d\u093e\u0917'),
        ),
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0907\u092e\u0947\u0932'),
        ),
        migrations.AlterField(
            model_name='office',
            name='fax',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u092b\u094d\u092f\u093e\u0915\u0938'),
        ),
        migrations.AlterField(
            model_name='office',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ompimage', verbose_name='\u0924\u0938\u094d\u092c\u093f\u0930'),
        ),
        migrations.AlterField(
            model_name='office',
            name='is_municipality',
            field=models.BooleanField(default=False, verbose_name='\u0928\u0917\u0930\u092a\u093e\u0932\u093f\u0915\u093e'),
        ),
        migrations.AlterField(
            model_name='office',
            name='is_project',
            field=models.BooleanField(default=False, verbose_name='\u0906\u092f\u094b\u091c\u0928\u093e'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u0928\u093e\u092e'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0915\u093e\u0930\u094d\u092f\u093e\u0932\u092f \u0938\u092e\u092f'),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u092b\u094b\u0928'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='budget',
            field=models.CharField(max_length=30, verbose_name='\u092c\u091c\u0947\u091f'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='chief_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u092c\u0930\u093f\u0938\u094d\u0920  \u0907\u0928\u094d\u091c\u093f\u0928\u0940\u092f\u0930'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='engineers',
            field=models.TextField(blank=True, verbose_name=' \u0907\u0928\u094d\u091c\u093f\u0928\u0940\u092f\u0930\u0939\u0930\u0941'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='objective',
            field=models.TextField(blank=True, verbose_name='\u0909\u0926\u094d\u0926\u0947\u0938\u094d\u092f'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='office',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_detail', to='office.Office', verbose_name='\u0915\u093e\u0930\u094d\u092f\u093e\u0932\u092f'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_time',
            field=models.CharField(max_length=30, verbose_name='\u0906\u092f\u094b\u091c\u0928\u093e\u0915\u094b \u0938\u092e\u092f'),
        ),
    ]
