# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20170622_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='district_np',
            new_name='district',
        ),
    ]
