# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20170622_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='district',
            field=models.ManyToManyField(related_name='office', to='office.District', verbose_name='\u091c\u093f\u0932\u094d\u0932\u093e'),
        ),
    ]
