# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_auto_20170622_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='office.Office', verbose_name='')),
            ],
        ),
    ]
