# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_officesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u0928\u093e\u092e'),
        ),
    ]
