# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20170623_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officesetting',
            name='office',
        ),
        migrations.DeleteModel(
            name='OfficeSetting',
        ),
    ]
